SUPABASE_URL = "https://gvumfapaqxdjozttwufa.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2dW1mYXBhcXhkam96dHR3dWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NjMwNDUsImV4cCI6MjA4NzIzOTA0NX0.PSC1x1QMHUu8_aWMYSMCubU_xXt27jorYZL-qwtIraI"
